name: Actualizar EC2 en commit a main

on:
  push:
    branches:
      - main

jobs:
  update-ec2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ec2_instance: 
          - ec2-18-206-199-236.compute-1.amazonaws.com
          - ec2-54-160-150-18.compute-1.amazonaws.com

    steps:
      - name: Configurando SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Actualizar repositorio en EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.ec2_instance }} "
          git config --global --add safe.directory /var/www/html &&
          cd /mnt/efs/html &&
          git reset --hard &&
          git pull origin main"

      - name: Reiniciar Servicio
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ matrix.ec2_instance }} "sudo systemctl restart nginx"

      - name: Eliminar clave SSH
        run: rm key.pem